1;
// console.log(018 - 015);
2;
// console.log(typeof typeof 1);
3;
// const numbers = [33, 2, 8];
// numbers.sort();
// console.log(numbers[1]);
4;
// console.log(false == "0");
5;
// console.log(0.1 + 0.2 == 0.3);
6;
// let array = [1, 2, 3];
// array[6] = 9;
// // console.log(array[5]);
// //some addition from me:
// const a = new Array(4);
// console.log(a);
// console.log(a[2]);
// a[2] = 21;
// console.log(a);
7;
// const isTrue = true == [];
// const isFalse = true == ![];
// console.log(isTrue + isFalse);
8;
// console.log(1 + "2" + "2");
9;
// console.log(String.raw`HelloTwitter\nworld`);
10;
console.log("This is a string." instanceof String);
